//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000-0000-0000-0000-000000000000,ZeroGuid
        ///00000000-0ED6-4E09-BBF9-28325DB6BA30,BSODDxeRuntime
        ///00026AEB-F334-4C15-A7F0-E1E897E9FE91,NvmeRecovery
        ///000AC7B6-F44D-4220-BD8B-521D30DEA80F,HpGraphicsDetectDxe
        ///000F42D0-283C-46AB-9287-ACB6C9941FCD,SmmSupvErrorReport
        ///0013BE6B-2198-43F1-93BA-2A7ED7B1E1CC,SystemUsbSwitchDxe
        ///00160F8D-2B35-4DF2-BBE0-B272A8D631F0,FirmwarePerformanceDxe
        ///001D24D1-4AB1-B202-42D1-0FB9F4E4AD36,BiosPowerOnPortingSmm
        ///0029231B-72EF-4FA5-BD37-7018A046FB0D,LenovoMultipleKeyboardService
        ///0029DE6A- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string guids {
            get {
                return ResourceManager.GetString("guids", resourceCulture);
            }
        }
    }
}
